version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: bike_tour_wp
    restart: always
    ports:
      - "4151:80"
    environment:
      WORDPRESS_DB_HOST: cafe_db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: mypassword
      WORDPRESS_DB_NAME: bwicycling
    volumes:
      - wp_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    networks:
      - cafe_network        

volumes:
  wp_data:

networks:
  cafe_network:
    external: true            # pakai network yang sudah ada
