services:
  wordpress:
    image: wordpress:latest
    container_name: bike_tour_wp
    restart: always
    ports:
      - "4151:80"
    environment:
      WORDPRESS_DB_HOST: cafe_db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: mypassword
      WORDPRESS_DB_NAME: bwicycling
    volumes:
      - wp_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    networks:
      - cafe-network

volumes:
  wp_data:

networks:
  cafe-network:
    external: true
